\section{reduce::reducemod::Ex\-Error Class Reference}
\label{classreduce_1_1reducemod_1_1ExError}\index{reduce::reducemod::ExError@{reduce::reducemod::ExError}}
\subsection*{Public Member Functions}
\begin{CompactItemize}
\item 
def \textbf{\_\-\_\-init\_\-\_\-}\label{classreduce_1_1reducemod_1_1ExError_0330672536e06b27cef962d3e0dafa4a}

\end{CompactItemize}
\subsection*{Public Attributes}
\begin{CompactItemize}
\item 
\textbf{args}\label{classreduce_1_1reducemod_1_1ExError_0b6c8c42abe094da494a9736530c0fe3}

\end{CompactItemize}


\subsection{Detailed Description}


\footnotesize\begin{verbatim}Module-specific error, to be raised when an 'expected' exception occurs
   during the processing of a task. This error should then be caught by the
   task manager, avoiding nasty error output.
\end{verbatim}
\normalsize
 



The documentation for this class was generated from the following file:\begin{CompactItemize}
\item 
reduce/reducemod.py\end{CompactItemize}
